In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("raw_market_data.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 288621 entries, 0 to 288620
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   timestamp  288621 non-null  object
 1   open       288621 non-null  float64
 2   high       288621 non-null  float64
 3   low        288621 non-null  float64
 4   close      288621 non-null  float64
 5   volume     288621 non-null  float64
dtypes: float64(5), object(1)
memory usage: 13.2+ MB

In [5]:
df.describe()

,open,high,low,close,volume
count,288621.000000,288621.000000,288621.000000,288621.000000,288621.000000
mean,38459.013931,38534.143984,38381.446577,38459.198379,667.397348
std,32487.083837,32534.650475,32438.392829,32487.100329,1070.495902
min,3166.110000,3174.780000,3156.260000,3167.070000,0.000000
25%,9586.000000,9605.220000,9563.850000,9585.890000,184.966150
50%,28412.970000,28466.000000,28359.650000,28413.110000,342.448976
75%,60250.000000,60390.010000,60122.500000,60250.000000,686.153970
max,126011.180000,126199.630000,125648.010000,126011.180000,40371.405060

In [6]:
df

,timestamp,open,high,low,close,volume
0,2017-12-31 21:00:00,13971.95,13976.30,13901.00,13942.27,91.942502
1,2017-12-31 21:15:00,13942.27,13975.10,13911.60,13920.03,54.117742
2,2017-12-31 21:30:00,13967.26,14005.00,13901.07,13915.22,60.598319
3,2017-12-31 21:45:00,13903.00,13976.92,13900.01,13940.99,33.125899
4,2017-12-31 22:00:00,13930.00,14012.00,13904.00,13911.00,77.166899
...,...,...,...,...,...,...
288616,2026-03-31 20:00:00,67838.79,68198.00,67831.70,68146.88,287.656470
288617,2026-03-31 20:15:00,68146.88,68167.44,67939.30,68003.00,222.554890
288618,2026-03-31 20:30:00,68003.01,68124.00,67953.37,68044.00,66.962920
288619,2026-03-31 20:45:00,68043.99,68267.27,68015.31,68265.53,115.891470
288620,2026-03-31 21:00:00,68265.53,68265.53,67962.05,68019.97,139.359510